USE jds;

delete from districts;
ALTER TABLE districts AUTO_INCREMENT = 1;

insert into districts

(district) VALUES
('24 Parganas North'), 
('24 Parganas South'), 
('Adilabad'), 
('Agra'), 
('Ahmedabad'), 
('Ahmednagar'), 
('Aizawl'), 
('Ajmer'), 
('Akola'), 
('Alappuzha'), 
('Aligarh'), 
('Allahabad'), 
('Almora'), 
('Alwar'), 
('Ambala'), 
('Ambedkar Nagar'), 
('Amravati'), 
('Amreli'), 
('Amritsar'), 
('Anand'), 
('Anantapur'), 
('Anantnag'), 
('Andaman Islands'), 
('Angul'), 
('Araria'), 
('Ariyalur'), 
('Auraiya'), 
('Aurangabad'), 
('Azamgarh'), 
('Badaun'), 
('Badgam'), 
('Bagalkot'), 
('Bageshwar'), 
('Baghpat'), 
('Bahraich'), 
('Balaghat'), 
('Baleshwar'), 
('Ballia'), 
('Balrampur'), 
('Banas Kantha'), 
('Banda'), 
('Bangalore Rural'), 
('Banka'), 
('Bankura'), 
('Banswara'), 
('Barabanki'), 
('Baragarh'), 
('Baramula'), 
('Baran'), 
('Bardhaman'), 
('Bareilly'), 
('Barmer'), 
('Barpeta'), 
('Barwani'), 
('Bastar'), 
('Basti'), 
('Bathinda'), 
('Begusarai'), 
('Belgaum'), 
('Bellary'), 
('Bengaluru'), 
('Betul'), 
('Bhadrak'), 
('Bhagalpur'), 
('Bhandara'), 
('Bharatpur'), 
('Bharuch'), 
('Bhavnagar'), 
('Bhilwara'), 
('Bhind'), 
('Bhiwani'), 
('Bhojpur'), 
('Bhopal'), 
('Bid'), 
('Bidar'), 
('Bijapur'), 
('Bijnor'), 
('Bikaner'), 
('Bilaspur'), 
('Birbhum'), 
('Bishnupur'), 
('Bokaro'), 
('Bolangir'), 
('Bongaigaon'), 
('Boudh'), 
('Bulandshahr'), 
('Buldhana'), 
('Bundi'), 
('Buxar'), 
('Cachar'), 
('Chamba'), 
('Chamoli'), 
('Champawat'), 
('Champhai'), 
('Chamrajnagar'), 
('Chandauli'), 
('Chandel'), 
('Chandigarh'), 
('Chandrapur'), 
('Changlang'), 
('Chatra'), 
('Chennai'), 
('Chhatarpur'), 
('Chhindwara'), 
('Chikmagalur'), 
('Chitradurga'), 
('Chitrakoot'), 
('Chittoor'), 
('Chittorgarh'), 
('Churachandpur'), 
('Churu'), 
('Coimbatore'), 
('Cuddalore'), 
('Cuddapah'), 
('Cuttack'), 
('Dadra and Nagar Haveli'), 
('Dahod'), 
('Dakshin Dinajpur'), 
('Dakshina Kannada'), 
('Daman'), 
('Damoh'), 
('Dantewada'), 
('Darbhanga'), 
('Darjeeling'), 
('Darrang'), 
('Datia'), 
('Dausa'), 
('Davanagere'), 
('Davangere'), 
('Dehradun'), 
('Delhi'), 
('Deogarh'), 
('Deoghar'), 
('Deoria'), 
('Dewas'), 
('Dhalai'), 
('Dhamtari'), 
('Dhanbad'), 
('Dhar'), 
('Dharmapuri'), 
('Dharwad'), 
('Dhemaji'), 
('Dhenkanal'), 
('Dholpur'), 
('Dhubri'), 
('Dhule'), 
('Dibang Valley'), 
('Dibrugarh'), 
('Dimapur'), 
('Dindigul'), 
('Dindori'), 
('Diu'), 
('Doda'), 
('Dumka'), 
('Dungarpur'), 
('Durg'), 
('East Garo Hills'), 
('East Godavari'), 
('East Imphal'), 
('East Kameng'), 
('East Khasi Hills'), 
('East Nimar'), 
('East Siang'), 
('East Sikkim'), 
('Ernakulam'), 
('Erode'), 
('Etah'), 
('Etawah'), 
('Faizabad'), 
('Faridabad'), 
('Faridkot'), 
('Farrukhabad'), 
('Fatehabad'), 
('Fatehgarh Sahib'), 
('Fatehpur'), 
('Firozabad'), 
('Firozpur'), 
('Gadag'), 
('Gadchiroli'), 
('Gajapati'), 
('Gandhinagar'), 
('Ganganagar'), 
('Ganjam'), 
('Garhwa'), 
('Garhwal'), 
('Gautam Buddha Nagar'), 
('Gaya'), 
('Ghaziabad'), 
('Ghazipur'), 
('Giridih'), 
('Goalpara'), 
('Godda'), 
('Golaghat'), 
('Gonda'), 
('Gondiya'), 
('Gopalganj'), 
('Gorakhpur'), 
('Gulbarga'), 
('Gumla'), 
('Guna'), 
('Guntur'), 
('Gurdaspur'), 
('Gurgaon'), 
('Gwalior'), 
('Hailakandi'), 
('Hamirpur'), 
('Hanumangarh'), 
('Harda'), 
('Hardoi'), 
('Haridwar'), 
('Hassan'), 
('Hathras'), 
('Haveri'), 
('Hazaribagh'), 
('Hingoli'), 
('Hissar'), 
('Hooghly'), 
('Hoshangabad'), 
('Hoshiarpur'), 
('Howrah'), 
('Hyderabad'), 
('Idukki'), 
('Indore'), 
('Jabalpur'), 
('Jagatsinghpur'), 
('Jaintia Hills'), 
('Jaipur'), 
('Jaisalmer'), 
('Jajpur'), 
('Jalandhar'), 
('Jalaun'), 
('Jalgaon'), 
('Jalna'), 
('Jalore'), 
('Jalpaiguri'), 
('Jammu'), 
('Jamnagar'), 
('Jamui'), 
('Janjgir-Champa'), 
('Jashpur'), 
('Jaunpur'), 
('Jehanabad'), 
('Jhabua'), 
('Jhajjar'), 
('Jhalawar'), 
('Jhansi'), 
('Jharsuguda'), 
('Jhunjhunun'), 
('Jind'), 
('Jodhpur'), 
('Jorhat'), 
('Junagadh'), 
('Jyotiba Phule Nagar'), 
('Kachchh'), 
('Kaimur'), 
('Kaithal'), 
('Kalahandi'), 
('Kamrup'), 
('Kancheepuram'), 
('Kandhamal'), 
('Kangra'), 
('Kanker'), 
('Kannauj'), 
('Kannur'), 
('Kanpur'), 
('Kanpur Dehat'), 
('Kanyakumari'), 
('Kapurthala'), 
('Karaikal'), 
('Karauli'), 
('Karbi Anglong'), 
('Kargil'), 
('Karimganj'), 
('Karimnagar'), 
('Karnal'), 
('Karur'), 
('Kasaragod'), 
('Kasargod'), 
('Kathua'), 
('Katihar'), 
('Katni'), 
('Kaushambi'), 
('Kawardha'), 
('Kendrapara'), 
('Keonjhar'), 
('Khagaria'), 
('Khammam'), 
('Kheda'), 
('Khordha'), 
('Kinnaur'), 
('Kishanganj'), 
('Koch Bihar'), 
('Kodagu'), 
('Koderma'), 
('Kohima'), 
('Kokrajhar'), 
('Kolar'), 
('Kolasib'), 
('Kolhapur'), 
('Kolkata'), 
('Kollam'), 
('Koppal'), 
('Koraput'), 
('Korba'), 
('Koriya'), 
('Kota'), 
('Kottayam'), 
('Kozhikode'), 
('Krishna'), 
('Kulu'), 
('Kupwara'), 
('Kurnool'), 
('Kurukshetra'), 
('Kushinagar'), 
('Lahaul and Spiti'), 
('Lakhimpur'), 
('Lakhimpur Kheri'), 
('Lakhisarai'), 
('Lakshadweep'), 
('Lalitpur'), 
('Latur'), 
('Lawngtlai'), 
('Leh'), 
('Lohardaga'), 
('Lohit'), 
('Lower Subansiri'), 
('Lucknow'), 
('Ludhiana'), 
('Lunglei'), 
('Madhepura'), 
('Madhubani'), 
('Madurai'), 
('Mahabubnagar'), 
('Maharajganj'), 
('Mahasamund'), 
('Mahe'), 
('Mahendragarh'), 
('Mahesana'), 
('Mahoba'), 
('Mainpuri'), 
('Malappuram'), 
('Malda'), 
('Malkangiri'), 
('Mamit'), 
('Mandi'), 
('Mandla'), 
('Mandsaur'), 
('Mandya'), 
('Mansa'), 
('Marigaon'), 
('Mathura'), 
('Maunathbhanjan'), 
('Mayurbhanj'), 
('Medak'), 
('Meerut'), 
('Midnapore'), 
('Mirzapur'), 
('Moga'), 
('Mokokchung'), 
('Mon'), 
('Moradabad'), 
('Morena'), 
('Muktsar'), 
('Mumbai City'), 
('Mumbai Suburban'), 
('Munger'), 
('Murshidabad'), 
('Muzaffarnagar'), 
('Muzaffarpur'), 
('Mysore'), 
('Nabarangpur'), 
('Nadia'), 
('Nagaon'), 
('Nagapattinam'), 
('Nagaur'), 
('Nagpur'), 
('Nainital'), 
('Nalanda'), 
('Nalbari'), 
('Nalgonda'), 
('Namakkal'), 
('Nanded'), 
('Nandurbar'), 
('Narmada'), 
('Narsinghpur'), 
('Nashik'), 
('Navsari'), 
('Nawada'), 
('Nawan Shehar'), 
('Nayagarh'), 
('Neemuch'), 
('Nellore'), 
('Nicobar Islands'), 
('Nilgiris'), 
('Nizamabad'), 
('North Cachar Hills'), 
('North Goa'), 
('North Sikkim'), 
('North Tripura'), 
('Nuapada'), 
('Osmanabad'), 
('Pakur'), 
('Palakkad'), 
('Palamu'), 
('Pali'), 
('Panch Mahals'), 
('Panchkula'), 
('Panipat'), 
('Panna'), 
('Papum Pare'), 
('Parbhani'), 
('Pashchim Champaran'), 
('Pashchim Singhbhum'), 
('Patan'), 
('Pathanamthitta'), 
('Patiala'), 
('Patna'), 
('Pauri Garhwal'), 
('Perambalur'), 
('Phek'), 
('Pilibhit'), 
('Pithoragarh'), 
('Poonch'), 
('Porbandar'), 
('Prakasam'), 
('Pratapgarh'), 
('Puducherry'), 
('Pudukkottai'), 
('Pulwama'), 
('Pune'), 
('Purba Champaran'), 
('Purba Singhbhum'), 
('Puri'), 
('Purnia'), 
('Purulia'), 
('Rae Bareli'), 
('Raichur'), 
('Raigarh'), 
('Raipur'), 
('Raisen'), 
('Rajauri'), 
('Rajgarh'), 
('Rajkot'), 
('Rajnandgaon'), 
('Rajsamand'), 
('Ramanathapuram'), 
('Rampur'), 
('Ranchi'), 
('Rangareddi'), 
('Ratlam'), 
('Ratnagiri'), 
('Rayagada'), 
('Rewa'), 
('Rewari'), 
('Ri-Bhoi'), 
('Rohtak'), 
('Rohtas'), 
('Rudra Prayag'), 
('Rupnagar'), 
('Sabar Kantha'), 
('Sagar'), 
('Saharanpur'), 
('Saharsa'), 
('Sahibganj'), 
('Saiha'), 
('Salem'), 
('Samastipur'), 
('Sambalpur'), 
('Sangli'), 
('Sangrur'), 
('Sant Kabir Nagar'), 
('Sant Ravi Das Nagar'), 
('Saran'), 
('Satara'), 
('Satna'), 
('Sawai Madhopur'), 
('Sehore'), 
('Senapati'), 
('Seoni'), 
('Serchhip'), 
('Shahdol'), 
('Shahjahanpur'), 
('Shajapur'), 
('Sheikhpura'), 
('Sheohar'), 
('Sheopur'), 
('Shimla'), 
('Shimoga'), 
('Shivpuri'), 
('Shravasti'), 
('Sibsagar'), 
('Siddharth Nagar'), 
('Sidhi'), 
('Sikar'), 
('Sindhudurg'), 
('Sirmaur'), 
('Sirohi'), 
('Sirsa'), 
('Sitamarhi'), 
('Sitapur'), 
('Sivaganga'), 
('Siwan'), 
('Solan'), 
('Solapur'), 
('Sonbhadra'), 
('Sonepat'), 
('Sonepur'), 
('Sonitpur'), 
('South Garo Hills'), 
('South Goa'), 
('South Sikkim'), 
('South Tripura'), 
('Srikakulam'), 
('Srinagar'), 
('Sultanpur'), 
('Sundargarh'), 
('Supaul'), 
('Surat'), 
('Surendranagar'), 
('Surguja'), 
('Tamenglong'), 
('Tawang'), 
('Tehri Garhwal'), 
('Thane'), 
('Thanjavur'), 
('The Dangs'), 
('Theni'), 
('Thiruvallur'), 
('Thiruvananthapuram'), 
('Thiruvarur'), 
('Thoothukudi'), 
('Thoubal'), 
('Thrissur'), 
('Tikamgarh'), 
('Tinsukia'), 
('Tirap'), 
('Tiruchirappalli'), 
('Tirunelveli'), 
('Tiruvannamalai'), 
('Tonk'), 
('Tuensang'), 
('Tumkur'), 
('Udaipur'), 
('Udham Singh Nagar'), 
('Udhampur'), 
('Udupi'), 
('Ujjain'), 
('Ukhrul'), 
('Umaria'), 
('Una'), 
('Unnao'), 
('Upper Siang'), 
('Upper Subansiri'), 
('Uttar Dinajpur'), 
('Uttara Kannada'), 
('Uttarkashi'), 
('Vadodara'), 
('Vaishali'), 
('Valsad'), 
('Varanasi'), 
('Vellore'), 
('Vidisha'), 
('Villupuram'), 
('Virudhunagar'), 
('Vishakhapatnam'), 
('Vizianagaram'), 
('Warangal'), 
('Wardha'), 
('Washim'), 
('Wayanad'), 
('West Garo Hills'), 
('West Godavari'), 
('West Imphal'), 
('West Kameng'), 
('West Khasi Hills'), 
('West Nimar'), 
('West Siang'), 
('West Sikkim'), 
('West Tripura'), 
('Wokha'), 
('Yamuna Nagar'), 
('Yamunanagar'), 
('Yanam'), 
('Yavatmal'), 
('Zunheboto')