USE jds;

delete from countries;
ALTER TABLE countries AUTO_INCREMENT = 1;

insert into countries
(country) VALUES
('Australia'),
('Afghanistan'),
('Argentina'),
('Bangladesh'),
('Bahrain'),
('Belgium'), 
('Brazil'), 
('Canada'),
('Chile'),
('China'),
('Congo'),
('Cuba'),
('Czech Republic'),
('Denmark'),
('Ethiopia'),
('Fiji'),
('Finland'),
('France'),
('Germany'),
('Greece'), 
('India'),
('Indonesia'),
('Iran'),
('Israel'), 
('Italy'), 
('Hong Kong'),
('Japan'),
('Jordan'),
('Kenya'),
('Kuwait'),
('Macedonia'),
('Madagascar'),
('Malaysia'),
('Mexico'),
('Moldava'),
('Mozambique'),
('Nepal'),  
('Netherlands'),
('New Zealand'), 
('Norway'),
('Pakistan'),
('Panama'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Russia'),
('Romania'), 
('Saudi Arabia'), 
('Singapore'),
('South Africa'),
('South Korea'),
('Spain'), 
('Sri Lanka'),
('Sweden'),
('Switzerland'), 
('Taiwan'),
('Thailand'),
('Uganda'), 
('UK'), 
('USA'),
('United Arab Emirates')