<?xml version="1.0" encoding="UTF-8"?>
<subscriptionlistXML>
    <page>1</page>
    <total>1</total>
    <records>1</records>
    <result>
        <subscriptionlist>
            <id>1</id>
            <journal_code>111</journal_code>
            <journal_name>Pramana</journal_name>
            <num_copies>4</num_copies>
            <start_year>2011</start_year>
            <num_years>4</num_years>            
        </subscriptionlist>
        <subscriptionlist>
            <id>2</id>
            <journal_code>131</journal_code>
            <journal_name>Pramana2</journal_name>
            <num_copies>4</num_copies>
            <start_year>2011</start_year>
            <num_years>4</num_years> 
        </subscriptionlist>
    </result>
</subscriptionlistXML>