USE jds;

delete from cities;
ALTER TABLE cities AUTO_INCREMENT = 1;

insert into cities
(city) VALUES
('Agra'), 
('Ahmedabad'), 
('Ahmednagar'), 
('Aizawl'), 
('Ajmer'), 
('Akola'), 
('Aligarh'), 
('Allahabad'), 
('Alwar'), 
('Ambattur'), 
('Ambernath'), 
('Amravati'), 
('Amritsar'), 
('Anantapur'), 
('Arrah'), 
('Asansol'), 
('Aurangabad'), 
('Avadi'), 
('Bally'), 
('Bangarpet'), 
('Baranagar'), 
('Bardhaman'), 
('Bareilly'), 
('Baripada'), 
('Bathinda'), 
('Belgaum'), 
('Bellary'), 
('Bengaluru'), 
('Bhagalpur'), 
('Bharatpur'), 
('Bhatpara'), 
('Bhavnagar'), 
('Bhilai'), 
('Bhilwara'), 
('Bhiwandi'), 
('Bhopal'), 
('Bhubaneswar'), 
('Bhuj'), 
('Bidar'), 
('Bidhan Nagar'), 
('Bihar Sharif'), 
('Bijapur'), 
('Bikaner'), 
('Bilaspur'), 
('Bokaro'), 
('Brahmapur'), 
('Chandigarh'), 
('Chandrapur'), 
('Chennai'), 
('Chittoor'), 
('Coimbatore'), 
('Cuttack'), 
('Darbhanga'), 
('Davanagere'), 
('Davangere'), 
('Dehradun'), 
('Delhi'), 
('Deoli'), 
('Dewas'), 
('Dhanbad'), 
('Dharwad'), 
('Dhule'), 
('Dona Paula'), 
('Durg'), 
('Durgapur'), 
('Ernakulam'), 
('Etawah'), 
('Faridabad'), 
('Farrukhabad'), 
('Firozabad'), 
('Gandhinagar'), 
('Gaya'), 
('Ghaziabad'), 
('Gopalpur'), 
('Gorakhpur'), 
('Gulbarga'), 
('Guntur'), 
('Gurgaon'), 
('Guwahati'), 
('Gwalior'), 
('Hapur'), 
('Hisar'), 
('Hosapete'), 
('Howrah'), 
('Hubballi-Dharwad'), 
('Hyderabad'), 
('Ichalkaranji'), 
('Imphal'), 
('Indore'), 
('Jabalpur'), 
('Jaipur'), 
('Jalandhar'), 
('Jalgaon'), 
('Jalna'), 
('Jammu'), 
('Jamnagar'), 
('Jamshedpur'), 
('Jhansi'), 
('Jodhpur'), 
('Kadapa'), 
('Kakinada'), 
('Kalpakkam'), 
('Kalyan-Dombivali'), 
('Kalyani'), 
('Kamarhati'), 
('Kanpur'), 
('Kanyakumari'), 
('Karaikkudi'), 
('Karimnagar'), 
('Kattankulathur'), 
('Kharagpur'), 
('Kishangarh'), 
('Kochi'), 
('Kolhapur'), 
('Kolkata'), 
('Kollam (Quilon)'), 
('Korba'), 
('Kota'), 
('Kozhikode (Calicut)'), 
('Krishangarh'), 
('Kulti'), 
('Kurnool'), 
('Kushalnagar'), 
('Latur'), 
('Loni'), 
('Lucknow'), 
('Ludhiana'), 
('Madurai'), 
('Maheshtala'), 
('Malegaon'), 
('Manauli'), 
('Mangalore'), 
('Manipal'), 
('Mathura'), 
('Mau'), 
('Meerut'), 
('Mira-Bhayandar'), 
('Mirzapur'), 
('Mohali'), 
('Moradabad'), 
('Mumbai'), 
('Muzaffarnagar'), 
('Muzaffarpur'), 
('Mysore'), 
('Nadia'), 
('Nagercoil'), 
('Nagpur'), 
('Naihati'), 
('Nainital'), 
('Nanded'), 
('Nangloi Jat'), 
('Nashik'), 
('Navi Mumbai'), 
('Nellore'), 
('New Delhi'), 
('Nizamabad'), 
('Noida'), 
('North Dumdum'), 
('Ozhukarai'), 
('Pali'), 
('Panchkula'), 
('Panihati'), 
('Panipat'), 
('Panvel'), 
('Parbhani'), 
('Patiala'), 
('Patna'), 
('Pimpri-Chinchwad'), 
('Prasanti Nilayam'), 
('Puducherry'), 
('Pune'), 
('Purnia'), 
('Radaur'), 
('Raichur'), 
('Raipur'), 
('Rajahmundry'), 
('Rajkot'), 
('Rajpur Sonarpur'), 
('Ramagundam'), 
('Rampur'), 
('Ranchi'), 
('Ratlam'), 
('Rewa'), 
('Rohtak'), 
('Roorkee'), 
('Sagar'), 
('Saharanpur'), 
('Salem'), 
('Sangli-Miraj & Kupwad'), 
('Santiniketan'), 
('SAS Nagar'), 
('Satna'), 
('Secunderabad'), 
('Shahjahanpur'), 
('Shillong'), 
('Shivamogga (Shimoga)'), 
('Silchar'), 
('Siliguri'), 
('Sindhudurg'), 
('Singrauli'), 
('Sivakasi'), 
('Solapur'), 
('Sonipat'), 
('South Dumdum'), 
('Sri Ganganagar'), 
('Srinagar'), 
('Sriperumbudur'), 
('Srirampur'), 
('Sultanpur'), 
('Surat'), 
('Surathkal'), 
('Tezpur'), 
('Thane'), 
('Thiruvananthapuram'), 
('Thrissur'), 
('Tiruchirapalli'), 
('Tirunelveli'), 
('Tirupati'), 
('Tirupur'), 
('Tiruvottiyur'), 
('Tumakuru (Tumkur)'), 
('Udaipur'), 
('Ujjain'), 
('Ulhasnagar'), 
('Uluberia'), 
('Vadodara'), 
('Vallabh Vidyanagar'), 
('Varanasi'), 
('Vasai-Virar'), 
('Vellore'), 
('Vijayawada'), 
('Visakhapatnam'), 
('Warangal'), 
('Yamunanagar'), 
('Yeddumailaram')