USE jds;

delete from countries;
ALTER TABLE countries AUTO_INCREMENT = 1;

insert into countries
(country) VALUES
('Australia'),
('Afghanistan'),
('Argentina'),
('Belgium'), 
('Brazil'), 
('Canada'),
('Chile'),
('China'),
('Czech Republic'),
('Denmark'),
('Finland'),
('France'),
('Germany'), 
('India'),
('Israel'), 
('Italy'), 
('Japan'),
('Jordan'),
('Macedonia'),
('Madagascar'),
('Malaysia'),
('Moldava'),
('Nepal'),  
('Netherlands'), 
('Norway'),
('Pakistan'),
('Poland'),
('Russia'),
('Romania'), 
('Saudi Arabia'), 
('Singapore'),
('Spain'), 
('Sri Lanka'),
('Sweden'),
('Switzerland'), 
('Taiwan'),
('Uganda'), 
('UK'), 
('USA')