function JDSConstants(){
    this.INWARD_PURPOSE_NEW_SUBSCRIPTION = 1;
    this.INWARD_PURPOSE_RENEW_SUBSCRIPTION = 2;
    this.INWARD_PURPOSE_ADDRESS_CHANGE = 3;
    this.INWARD_PURPOSE_REQUEST_FOR_INVOICE = 4;

}


